// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcvIH6fOMjBlUYLc-q4ZTgMnCi-FOlMmw',
    appId: '1:746888858332:web:05bbe713ae1b4066808219',
    messagingSenderId: '746888858332',
    projectId: 'safenetvpn-e2446',
    authDomain: 'safenetvpn-e2446.firebaseapp.com',
    storageBucket: 'safenetvpn-e2446.firebasestorage.app',
    measurementId: 'G-DJ4XPSXVEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChkNWPlvOof5VHS7fsNpYCrGOc2VNB3jo',
    appId: '1:746888858332:android:ed9c362e04dd9f0e808219',
    messagingSenderId: '746888858332',
    projectId: 'safenetvpn-e2446',
    storageBucket: 'safenetvpn-e2446.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAry0s8oOATcH7tTfj4-QzHyhT1dSJZwo4',
    appId: '1:746888858332:ios:abba265933c2ffd1808219',
    messagingSenderId: '746888858332',
    projectId: 'safenetvpn-e2446',
    storageBucket: 'safenetvpn-e2446.firebasestorage.app',
    iosBundleId: 'com.example.safenetvpn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAry0s8oOATcH7tTfj4-QzHyhT1dSJZwo4',
    appId: '1:746888858332:ios:abba265933c2ffd1808219',
    messagingSenderId: '746888858332',
    projectId: 'safenetvpn-e2446',
    storageBucket: 'safenetvpn-e2446.firebasestorage.app',
    iosBundleId: 'com.example.safenetvpn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcvIH6fOMjBlUYLc-q4ZTgMnCi-FOlMmw',
    appId: '1:746888858332:web:ed9e83c95cf8ea11808219',
    messagingSenderId: '746888858332',
    projectId: 'safenetvpn-e2446',
    authDomain: 'safenetvpn-e2446.firebaseapp.com',
    storageBucket: 'safenetvpn-e2446.firebasestorage.app',
    measurementId: 'G-X0Q1RWMB0T',
  );

}